version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        environment:
          RAILS_ENV: test
          TEST_DATABASE_NAME: test_db
          TEST_DATABASE_USERNAME: user
          TEST_DATABASE_PASSWORD: passw0rd
      - image: circleci/mysql:8.0.4
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd

    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run: cd spec/dummy && bundle install --path vendor/bundle
      - run: cd spec/dummy && yarn install
      - run: cd spec/dummy && bundle exec rails mokio:install:migrations
      - run: cd spec/dummy && bundle exec rails db:create
      - run: cd spec/dummy && bundle exec rails db:migrate
      - run: bundle exec rspec
